name: Doxygen Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install doxygen
      - name: Generate Documentation
        run: doxygen Doxyfile
      - name: Check for Warnings
        run: |
          if grep -q "warning:" docs/html/index.html; then
            echo "Doxygen found warnings."
            exit 1
          else
            echo "No Doxygen warnings found."
          fi
      - name: Upload Documentation Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: doxygen-docs
          path: docs/html
